# Generated by Django 4.2.4 on 2023-10-23 09:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companyshares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='name',
        ),
        migrations.AddField(
            model_name='shares',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата выпуска акции'),
        ),
        migrations.AlterField(
            model_name='shares',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company', to='companyshares.company', verbose_name='какой компании принадлежит акция'),
        ),
    ]
