# Generated by Django 4.2.4 on 2023-10-23 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyshares', '0002_remove_company_date_create_remove_shares_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company', to='companyshares.company', verbose_name='какой компании принадлежит акция'),
        ),
    ]
