# Generated by Django 4.2.4 on 2023-10-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyshares', '0004_shares_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступны для покупки'),
        ),
    ]
